// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SileroVadModelConfig {
  final String model;
  final double threshold;
  final int sampleRate;
  final double minSilenceDuration;
  final double minSpeechDuration;
  final double maxSpeechDuration;
  final int speechPadMs;

  const SileroVadModelConfig({
    required this.model,
    required this.threshold,
    required this.sampleRate,
    required this.minSilenceDuration,
    required this.minSpeechDuration,
    required this.maxSpeechDuration,
    required this.speechPadMs,
  });

  @override
  int get hashCode =>
      model.hashCode ^
      threshold.hashCode ^
      sampleRate.hashCode ^
      minSilenceDuration.hashCode ^
      minSpeechDuration.hashCode ^
      maxSpeechDuration.hashCode ^
      speechPadMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SileroVadModelConfig &&
          runtimeType == other.runtimeType &&
          model == other.model &&
          threshold == other.threshold &&
          sampleRate == other.sampleRate &&
          minSilenceDuration == other.minSilenceDuration &&
          minSpeechDuration == other.minSpeechDuration &&
          maxSpeechDuration == other.maxSpeechDuration &&
          speechPadMs == other.speechPadMs;
}
