// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/common.dart';
import 'api/online.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models/sense_voice/sense_voice.dart';
import 'models/vad.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCommonInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1445677170;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_opencode_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AsrSettings> crateApiCommonAsrSettingsDefault();

  Future<SenseVoiceConfig> crateApiCommonBuildAsrConfig({
    required String modelPath,
    required String vocabPath,
    required AsrSettings settings,
  });

  Future<SileroVadModelConfig> crateApiCommonBuildVadConfig({
    required String modelPath,
    required VadSettings settings,
  });

  Future<void> crateApiCommonConfigureOnnxruntimeDylib();

  Future<String> crateApiCommonEscapeJsonString({required String input});

  Future<void> crateApiOnlineFinishOnlineAudioSource({required String source});

  Future<String> crateApiCommonGreet({required String name});

  Future<void> crateApiCommonInitApp();

  Future<double> crateApiCommonNormalizeConfidence({
    required double confidence,
  });

  Future<void> crateApiOnlinePushOnlineAudio({
    required String source,
    required List<int> pcmS16Le,
    required int sampleRate,
  });

  Stream<String> crateApiOnlineRunOnlineTranscription({
    required String modelPath,
    required String vocabPath,
    required String vadModelPath,
    required String onnxruntimePath,
    required AsrSettings asrSettings,
    required VadSettings vadSettings,
  });

  Stream<String> crateApiSimpleRunOnlineTranscription({
    required String modelPath,
    required String vocabPath,
    required String vadModelPath,
    required AsrSettings asrSettings,
    required VadSettings vadSettings,
  });

  Future<void> crateApiOnlineStopOnlineTranscription();

  Future<VadSettings> crateApiCommonVadSettingsDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AsrSettings> crateApiCommonAsrSettingsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_asr_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonAsrSettingsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonAsrSettingsDefaultConstMeta =>
      const TaskConstMeta(debugName: "asr_settings_default", argNames: []);

  @override
  Future<SenseVoiceConfig> crateApiCommonBuildAsrConfig({
    required String modelPath,
    required String vocabPath,
    required AsrSettings settings,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(vocabPath, serializer);
          sse_encode_box_autoadd_asr_settings(settings, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sense_voice_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonBuildAsrConfigConstMeta,
        argValues: [modelPath, vocabPath, settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonBuildAsrConfigConstMeta =>
      const TaskConstMeta(
        debugName: "build_asr_config",
        argNames: ["modelPath", "vocabPath", "settings"],
      );

  @override
  Future<SileroVadModelConfig> crateApiCommonBuildVadConfig({
    required String modelPath,
    required VadSettings settings,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_box_autoadd_vad_settings(settings, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_silero_vad_model_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonBuildVadConfigConstMeta,
        argValues: [modelPath, settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonBuildVadConfigConstMeta =>
      const TaskConstMeta(
        debugName: "build_vad_config",
        argNames: ["modelPath", "settings"],
      );

  @override
  Future<void> crateApiCommonConfigureOnnxruntimeDylib() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonConfigureOnnxruntimeDylibConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonConfigureOnnxruntimeDylibConstMeta =>
      const TaskConstMeta(
        debugName: "configure_onnxruntime_dylib",
        argNames: [],
      );

  @override
  Future<String> crateApiCommonEscapeJsonString({required String input}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonEscapeJsonStringConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonEscapeJsonStringConstMeta =>
      const TaskConstMeta(debugName: "escape_json_string", argNames: ["input"]);

  @override
  Future<void> crateApiOnlineFinishOnlineAudioSource({required String source}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiOnlineFinishOnlineAudioSourceConstMeta,
        argValues: [source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOnlineFinishOnlineAudioSourceConstMeta =>
      const TaskConstMeta(
        debugName: "finish_online_audio_source",
        argNames: ["source"],
      );

  @override
  Future<String> crateApiCommonGreet({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiCommonInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<double> crateApiCommonNormalizeConfidence({
    required double confidence,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(confidence, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonNormalizeConfidenceConstMeta,
        argValues: [confidence],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonNormalizeConfidenceConstMeta =>
      const TaskConstMeta(
        debugName: "normalize_confidence",
        argNames: ["confidence"],
      );

  @override
  Future<void> crateApiOnlinePushOnlineAudio({
    required String source,
    required List<int> pcmS16Le,
    required int sampleRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_list_prim_u_8_loose(pcmS16Le, serializer);
          sse_encode_u_32(sampleRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiOnlinePushOnlineAudioConstMeta,
        argValues: [source, pcmS16Le, sampleRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOnlinePushOnlineAudioConstMeta =>
      const TaskConstMeta(
        debugName: "push_online_audio",
        argNames: ["source", "pcmS16Le", "sampleRate"],
      );

  @override
  Stream<String> crateApiOnlineRunOnlineTranscription({
    required String modelPath,
    required String vocabPath,
    required String vadModelPath,
    required String onnxruntimePath,
    required AsrSettings asrSettings,
    required VadSettings vadSettings,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(modelPath, serializer);
            sse_encode_String(vocabPath, serializer);
            sse_encode_String(vadModelPath, serializer);
            sse_encode_String(onnxruntimePath, serializer);
            sse_encode_box_autoadd_asr_settings(asrSettings, serializer);
            sse_encode_box_autoadd_vad_settings(vadSettings, serializer);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiOnlineRunOnlineTranscriptionConstMeta,
          argValues: [
            modelPath,
            vocabPath,
            vadModelPath,
            onnxruntimePath,
            asrSettings,
            vadSettings,
            sink,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiOnlineRunOnlineTranscriptionConstMeta =>
      const TaskConstMeta(
        debugName: "run_online_transcription",
        argNames: [
          "modelPath",
          "vocabPath",
          "vadModelPath",
          "onnxruntimePath",
          "asrSettings",
          "vadSettings",
          "sink",
        ],
      );

  @override
  Stream<String> crateApiSimpleRunOnlineTranscription({
    required String modelPath,
    required String vocabPath,
    required String vadModelPath,
    required AsrSettings asrSettings,
    required VadSettings vadSettings,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(modelPath, serializer);
            sse_encode_String(vocabPath, serializer);
            sse_encode_String(vadModelPath, serializer);
            sse_encode_box_autoadd_asr_settings(asrSettings, serializer);
            sse_encode_box_autoadd_vad_settings(vadSettings, serializer);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 12,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSimpleRunOnlineTranscriptionConstMeta,
          argValues: [
            modelPath,
            vocabPath,
            vadModelPath,
            asrSettings,
            vadSettings,
            sink,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleRunOnlineTranscriptionConstMeta =>
      const TaskConstMeta(
        debugName: "run_online_transcription",
        argNames: [
          "modelPath",
          "vocabPath",
          "vadModelPath",
          "asrSettings",
          "vadSettings",
          "sink",
        ],
      );

  @override
  Future<void> crateApiOnlineStopOnlineTranscription() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiOnlineStopOnlineTranscriptionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOnlineStopOnlineTranscriptionConstMeta =>
      const TaskConstMeta(debugName: "stop_online_transcription", argNames: []);

  @override
  Future<VadSettings> crateApiCommonVadSettingsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vad_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommonVadSettingsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommonVadSettingsDefaultConstMeta =>
      const TaskConstMeta(debugName: "vad_settings_default", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AsrSettings dco_decode_asr_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AsrSettings(
      language: dco_decode_String(arr[0]),
      useItn: dco_decode_bool(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AsrSettings dco_decode_box_autoadd_asr_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_asr_settings(raw);
  }

  @protected
  VadSettings dco_decode_box_autoadd_vad_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vad_settings(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SenseVoiceConfig dco_decode_sense_voice_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SenseVoiceConfig(
      modelPath: dco_decode_String(arr[0]),
      vocabPath: dco_decode_String(arr[1]),
      language: dco_decode_String(arr[2]),
      useItn: dco_decode_bool(arr[3]),
    );
  }

  @protected
  SileroVadModelConfig dco_decode_silero_vad_model_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SileroVadModelConfig(
      model: dco_decode_String(arr[0]),
      threshold: dco_decode_f_32(arr[1]),
      sampleRate: dco_decode_i_32(arr[2]),
      minSilenceDuration: dco_decode_f_32(arr[3]),
      minSpeechDuration: dco_decode_f_32(arr[4]),
      maxSpeechDuration: dco_decode_f_32(arr[5]),
      speechPadMs: dco_decode_i_32(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VadSettings dco_decode_vad_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return VadSettings(
      threshold: dco_decode_f_32(arr[0]),
      minSilenceDuration: dco_decode_f_32(arr[1]),
      minSpeechDuration: dco_decode_f_32(arr[2]),
      maxSpeechDuration: dco_decode_f_32(arr[3]),
      speechPadMs: dco_decode_i_32(arr[4]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AsrSettings sse_decode_asr_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_language = sse_decode_String(deserializer);
    var var_useItn = sse_decode_bool(deserializer);
    return AsrSettings(language: var_language, useItn: var_useItn);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AsrSettings sse_decode_box_autoadd_asr_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_asr_settings(deserializer));
  }

  @protected
  VadSettings sse_decode_box_autoadd_vad_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vad_settings(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SenseVoiceConfig sse_decode_sense_voice_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modelPath = sse_decode_String(deserializer);
    var var_vocabPath = sse_decode_String(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_useItn = sse_decode_bool(deserializer);
    return SenseVoiceConfig(
      modelPath: var_modelPath,
      vocabPath: var_vocabPath,
      language: var_language,
      useItn: var_useItn,
    );
  }

  @protected
  SileroVadModelConfig sse_decode_silero_vad_model_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_model = sse_decode_String(deserializer);
    var var_threshold = sse_decode_f_32(deserializer);
    var var_sampleRate = sse_decode_i_32(deserializer);
    var var_minSilenceDuration = sse_decode_f_32(deserializer);
    var var_minSpeechDuration = sse_decode_f_32(deserializer);
    var var_maxSpeechDuration = sse_decode_f_32(deserializer);
    var var_speechPadMs = sse_decode_i_32(deserializer);
    return SileroVadModelConfig(
      model: var_model,
      threshold: var_threshold,
      sampleRate: var_sampleRate,
      minSilenceDuration: var_minSilenceDuration,
      minSpeechDuration: var_minSpeechDuration,
      maxSpeechDuration: var_maxSpeechDuration,
      speechPadMs: var_speechPadMs,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VadSettings sse_decode_vad_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_threshold = sse_decode_f_32(deserializer);
    var var_minSilenceDuration = sse_decode_f_32(deserializer);
    var var_minSpeechDuration = sse_decode_f_32(deserializer);
    var var_maxSpeechDuration = sse_decode_f_32(deserializer);
    var var_speechPadMs = sse_decode_i_32(deserializer);
    return VadSettings(
      threshold: var_threshold,
      minSilenceDuration: var_minSilenceDuration,
      minSpeechDuration: var_minSpeechDuration,
      maxSpeechDuration: var_maxSpeechDuration,
      speechPadMs: var_speechPadMs,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_asr_settings(AsrSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.language, serializer);
    sse_encode_bool(self.useItn, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_asr_settings(
    AsrSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_asr_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vad_settings(
    VadSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vad_settings(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_sense_voice_config(
    SenseVoiceConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.modelPath, serializer);
    sse_encode_String(self.vocabPath, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_bool(self.useItn, serializer);
  }

  @protected
  void sse_encode_silero_vad_model_config(
    SileroVadModelConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.model, serializer);
    sse_encode_f_32(self.threshold, serializer);
    sse_encode_i_32(self.sampleRate, serializer);
    sse_encode_f_32(self.minSilenceDuration, serializer);
    sse_encode_f_32(self.minSpeechDuration, serializer);
    sse_encode_f_32(self.maxSpeechDuration, serializer);
    sse_encode_i_32(self.speechPadMs, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vad_settings(VadSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.threshold, serializer);
    sse_encode_f_32(self.minSilenceDuration, serializer);
    sse_encode_f_32(self.minSpeechDuration, serializer);
    sse_encode_f_32(self.maxSpeechDuration, serializer);
    sse_encode_i_32(self.speechPadMs, serializer);
  }
}
