// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SenseVoiceConfig {
  final String modelPath;
  final String vocabPath;
  final String language;
  final bool useItn;

  const SenseVoiceConfig({
    required this.modelPath,
    required this.vocabPath,
    required this.language,
    required this.useItn,
  });

  @override
  int get hashCode =>
      modelPath.hashCode ^
      vocabPath.hashCode ^
      language.hashCode ^
      useItn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenseVoiceConfig &&
          runtimeType == other.runtimeType &&
          modelPath == other.modelPath &&
          vocabPath == other.vocabPath &&
          language == other.language &&
          useItn == other.useItn;
}
