[package]
name = "rust_lib_opencode_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
ort = { version = "=2.0.0-rc.12", features = ["load-dynamic"] }
ndarray = { version = "0.17" }
anyhow = "1.0"
kaldi-fbank-rust-kautism = "0.1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
log = "0.4"
android_logger = "0.13" # For android logging
rubato = "4.0.0" # High-quality resampling
ringbuf = "0.4.8" # Lock-free ring buffer for audio
audioadapter-buffers = "4.0" # For rubato adapters
rayon = "1.10"
futures = "0.3"
tokio = { version = "1", features = ["full"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
