// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/sense_voice/sense_voice.dart';
import '../models/vad.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `debug_marker`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioDevice`, `TranscribeResult`, `VadSegment`

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiCommonGreet(name: name);

Future<SenseVoiceConfig> buildAsrConfig({
  required String modelPath,
  required String vocabPath,
  required AsrSettings settings,
}) => RustLib.instance.api.crateApiCommonBuildAsrConfig(
  modelPath: modelPath,
  vocabPath: vocabPath,
  settings: settings,
);

Future<SileroVadModelConfig> buildVadConfig({
  required String modelPath,
  required VadSettings settings,
}) => RustLib.instance.api.crateApiCommonBuildVadConfig(
  modelPath: modelPath,
  settings: settings,
);

Future<double> normalizeConfidence({required double confidence}) => RustLib
    .instance
    .api
    .crateApiCommonNormalizeConfidence(confidence: confidence);

Future<String> escapeJsonString({required String input}) =>
    RustLib.instance.api.crateApiCommonEscapeJsonString(input: input);

Future<void> configureOnnxruntimeDylib() =>
    RustLib.instance.api.crateApiCommonConfigureOnnxruntimeDylib();

class AsrSettings {
  final String language;
  final bool useItn;

  const AsrSettings({required this.language, required this.useItn});

  static Future<AsrSettings> default_() =>
      RustLib.instance.api.crateApiCommonAsrSettingsDefault();

  @override
  int get hashCode => language.hashCode ^ useItn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AsrSettings &&
          runtimeType == other.runtimeType &&
          language == other.language &&
          useItn == other.useItn;
}

class VadSettings {
  final double threshold;
  final double minSilenceDuration;
  final double minSpeechDuration;
  final double maxSpeechDuration;
  final int speechPadMs;

  const VadSettings({
    required this.threshold,
    required this.minSilenceDuration,
    required this.minSpeechDuration,
    required this.maxSpeechDuration,
    required this.speechPadMs,
  });

  static Future<VadSettings> default_() =>
      RustLib.instance.api.crateApiCommonVadSettingsDefault();

  @override
  int get hashCode =>
      threshold.hashCode ^
      minSilenceDuration.hashCode ^
      minSpeechDuration.hashCode ^
      maxSpeechDuration.hashCode ^
      speechPadMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VadSettings &&
          runtimeType == other.runtimeType &&
          threshold == other.threshold &&
          minSilenceDuration == other.minSilenceDuration &&
          minSpeechDuration == other.minSpeechDuration &&
          maxSpeechDuration == other.maxSpeechDuration &&
          speechPadMs == other.speechPadMs;
}
