// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<String> runOnlineTranscription({
  required String modelPath,
  required String vocabPath,
  required String vadModelPath,
  required String onnxruntimePath,
  required AsrSettings asrSettings,
  required VadSettings vadSettings,
}) => RustLib.instance.api.crateApiOnlineRunOnlineTranscription(
  modelPath: modelPath,
  vocabPath: vocabPath,
  vadModelPath: vadModelPath,
  onnxruntimePath: onnxruntimePath,
  asrSettings: asrSettings,
  vadSettings: vadSettings,
);

Future<void> pushOnlineAudio({
  required String source,
  required List<int> pcmS16Le,
  required int sampleRate,
}) => RustLib.instance.api.crateApiOnlinePushOnlineAudio(
  source: source,
  pcmS16Le: pcmS16Le,
  sampleRate: sampleRate,
);

Future<void> finishOnlineAudioSource({required String source}) =>
    RustLib.instance.api.crateApiOnlineFinishOnlineAudioSource(source: source);

Future<void> stopOnlineTranscription() =>
    RustLib.instance.api.crateApiOnlineStopOnlineTranscription();
